In [3]:
import numpy as np
from scipy.optimize import minimize

# load params
mu = np.load("project3_outputs/mu_hat.npy")
Sigma = np.load("project3_outputs/Sigma_hat.npy")
gamma = 3.0
ones = np.array([1, 1, 1])
assets = ["SPY", "IEF", "GLD"]

print(f"mu    = {mu}")
print(f"gamma = {gamma}")
print(f"Sigma =")
for row in Sigma:
    print(f"        {row}")
print()

mu    = [ 0.00051575 -0.00024641  0.00032329]
gamma = 3.0
Sigma =
        [1.08500755e-04 5.42930040e-06 1.54645268e-05]
        [5.4293004e-06 2.6382581e-05 1.8884914e-05]
        [1.54645268e-05 1.88849140e-05 8.14528009e-05]



Unconstrained Optimal Portfolio
Closed form: w* = Σ⁻¹1/(1ᵀΣ⁻¹1) + (1/γ) Σ⁻¹(μ - (1ᵀΣ⁻¹μ)/(1ᵀΣ⁻¹1) · 1)

In [6]:
#Σ⁻¹
sigma_inv = np.linalg.inv(Sigma)

#Σ⁻¹𝟏
sigma_inv_ones = sigma_inv @ ones


GMVP = sigma_inv_ones / (ones @ sigma_inv_ones)

speculative = 1 / gamma * sigma_inv @ (mu - (ones @ sigma_inv @ mu) / (ones @ sigma_inv_ones) * ones)

w_star = GMVP + speculative

# stats
portfolio_mean = mu @ w_star
portfolio_var = w_star @ Sigma @ w_star
portfolio_utility = portfolio_mean - 0.5 * gamma * portfolio_var

print(f"GMVP component:        {np.round(GMVP, 6)}")
print(f"Speculative component: {np.round(speculative, 6)}")

for i, asset in enumerate(assets):
    print(f"w*_{asset} = {w_star[i]:+.6f}")

print(f"\nSum of weights:     {w_star.sum():.6f}")
print(f"Portfolio mean:     {portfolio_mean:.8f}")
print(f"Portfolio variance: {portfolio_var:.10f}")
print(f"Portfolio utility:  {portfolio_utility:.8f}")
print()

GMVP component:        [0.159458 0.773435 0.067107]
Speculative component: [ 1.726325 -4.004652  2.278327]
w*_SPY = +1.885783
w*_IEF = -3.231217
w*_GLD = +2.345434

Sum of weights:     1.000000
Portfolio mean:     0.00252705
Portfolio variance: 0.0008937694
Portfolio utility:  0.00118639

